### ISSUE TITLE
Incompatible with Gnome 41.1

### ISSUE THREAD

**Issue by Kivarnis** [cansozbir/gnome-shell-toggle-night-light-extension#7]
As the title says this is now incompatible with gnome as of 41.1, rely on this extension at night. Not sure what other info to post here.

**Comment by cansozbir** [comment]
I just added gnome 41 to the metadata of the extension, but could not try it myself. If you can test it and inform me, I would really appreciate this, then I can update the extension on the store. Otherwise, I will download gnome41 to try it in 1 or 2 days.

You can try manual installation of [this branch](/cansozbir/gnome-shell-toggle-night-light-extension/tree/gnome-41), or more easily add 41 to shell version in metadata.json file, the extension is generally installed at " ~/.local/share/gnome-shell/extensions/" AFAIK.

```
"shell-version": [
        "3.36",
        "3.38",
        "40",
        "41"
    ],
```

**Comment by roshanshariff** [comment]
I made that change to metadata.json and your extension works perfectly in Gnome 41. Thank you!

**Comment by cansozbir** [comment]
Okay, then we can merge it to the master. In GNOME, we trust :)
